@startuml AddItemRecipeUseCase
' Pantry Planner Add Item use case.'

left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor User
actor Database

rectangle "Home Screen\n Add Item, Recipe"{
    (Press Add Button) as addButton
    (Show Selection Screen) as selMenu
    (Select Add Item or Recipe) as selOption
    (Show Add Item or Recipe Form) as showForm
    (Fill Out Form Information) as addInfo
    (Press Save Button) as saveButton
    (Ask for Save Confirmation) as saveConf
    (Confirm Save) as confSave
    (Prepare and Send \nAdd Message to Database) as saveData
    (Send Confirmation Result) as sendResult
    (Show Save Result) as showResult
}

User --> addButton
User <-- selMenu
User --> selOption
User <-- showForm
User --> addInfo
User --> saveButton
User <-- saveConf
User --> confSave
confSave --> saveData
saveData --> Database
sendResult <-- Database
showResult <-- sendResult
User <-- showResult

@enduml
