@startuml AddItemUseCase

left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor User
actor Database

rectangle "Pantry Planner Item View"{
    usecase "Press edit item button" as editButton
    usecase "Send Edit Mode Confirmation" as editModeConf
    usecase "Confirm Edit Mode" as confMode
    usecase "Edit the fields" as editInfo
    usecase "Press save button" as saveButton
    usecase "Confirm Save Prompt" as saveConfPrompt
    usecase "Confirm Save" as saveConf
    usecase "Update the entry by unique id" as updateDB
    usecase "Send result of update" as sendResult
}

User --> (editButton)
User <-- editModeConf
User --> (confMode)
User --> (editInfo)
User --> saveButton
User <-- saveConfPrompt
User --> saveConf
saveConf --> updateDB : confirmed
updateDB --> Database
(sendResult) <-- Database

@enduml
