@startuml SearchUseCase

left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor User
actor Database

rectangle "Item and Recipe Search "{
    usecase "Press Search Button" as searchButton
    usecase "Edit Search Entry" as enterSearch
    (Confirm Search) as confSearch
    (Build and Send Search Request) as sendReq
    (Send Results) as sendResult
    (Show Results) as resultScreen
}

User --> searchBar
User --> enterSearch
User --> confSearch
confSearch --> sendReq
sendReq --> Database
sendResult <-- Database
resultScreen <-- sendResult

@enduml
