@startuml AddItemUseCase
' Pantry Planner Add Recipe use case.'

left to right direction
skinparam actorStyle awesome
skinparam packageStyle rectangle

actor User
actor Database

rectangle "Add Recipe - Home Screen"{
    usecase "Press Add Recipe" as addButton
    usecase "Show Add Recipe Form" as showForm
    usecase "Edit Recipe Form" as editForm
    usecase "Press Save Button" as saveButton
    usecase "Confirm Save from User" as confSave
    usecase "Press Save Confirm" as saveConf
    usecase "Store Data" as saveData
    usecase "Send Save Result" as sendResult
    usecase "Show Save Result" as showResult
}

User --> addButton
User <-- showForm
User --> editForm
User --> saveButton
User <-- confSave
User --> saveConf
saveConf --> saveData
saveData --> Database
sendResult <-- Database
showResult <-- sendResult

@enduml
